 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubmissionId = IDL.Nat;
export const FullName = IDL.Text;
export const Email = IDL.Text;
export const ServiceInterest = IDL.Text;
export const Message = IDL.Text;
export const Timestamp = IDL.Int;
export const PhoneNumber = IDL.Text;
export const ContactSubmission = IDL.Record({
  'id' : SubmissionId,
  'fullName' : FullName,
  'email' : Email,
  'serviceInterest' : ServiceInterest,
  'message' : Message,
  'timestamp' : Timestamp,
  'phoneNumber' : PhoneNumber,
});

export const idlService = IDL.Service({
  'deleteSubmission' : IDL.Func([SubmissionId], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getSubmissionById' : IDL.Func(
      [SubmissionId],
      [ContactSubmission],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [FullName, Email, PhoneNumber, ServiceInterest, Message],
      [SubmissionId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubmissionId = IDL.Nat;
  const FullName = IDL.Text;
  const Email = IDL.Text;
  const ServiceInterest = IDL.Text;
  const Message = IDL.Text;
  const Timestamp = IDL.Int;
  const PhoneNumber = IDL.Text;
  const ContactSubmission = IDL.Record({
    'id' : SubmissionId,
    'fullName' : FullName,
    'email' : Email,
    'serviceInterest' : ServiceInterest,
    'message' : Message,
    'timestamp' : Timestamp,
    'phoneNumber' : PhoneNumber,
  });
  
  return IDL.Service({
    'deleteSubmission' : IDL.Func([SubmissionId], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getSubmissionById' : IDL.Func(
        [SubmissionId],
        [ContactSubmission],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [FullName, Email, PhoneNumber, ServiceInterest, Message],
        [SubmissionId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };